name: edukonsel
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  auto_route: ^5.0.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.1.0
  cloud_functions: ^4.0.5
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.6
  dio_smart_retry: ^1.4.0
  equatable: ^2.0.5
  faker: ^2.1.0
  file_picker: ^5.2.4
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_messaging: ^14.1.2
  firebase_performance: ^0.9.0+6
  firebase_storage: ^11.0.6
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  graphql_flutter: ^5.1.0
  image_picker: ^0.8.6
  injectable: ^2.0.1
  intl: ^0.18.0
  logger: ^1.1.0
  m_toast: ^0.1.8
  pin_code_text_field: ^1.8.0
  quickalert: ^1.0.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  validators: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.4.0
  multi_select_flutter: ^4.1.3
  youtube_player_iframe: ^2.2.2
  timeago: ^3.3.0
  date_format: ^2.0.7
  table_calendar: ^3.0.9
  agora_rtc_engine: ^6.2.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  dart_code_metrics: ^5.2.1
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.15
  freezed: ^2.2.1
  injectable_generator: ^2.0.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.4
  lint: ^2.0.1
  build_runner:

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 900
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300

  assets:
    - assets/icons/
    - assets/images/
    - assets/illustrations/