// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwwfg0irVaToPVlmMsHYqPgk5G0SDH9Q',
    appId: '1:1024826384819:web:6cd36f70b524ad04972bc6',
    messagingSenderId: '1024826384819',
    projectId: 'edukonsel',
    authDomain: 'edukonsel.firebaseapp.com',
    storageBucket: 'edukonsel.appspot.com',
    measurementId: 'G-2YZWKJPE59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE9x4wouJC_2-pJwN9l8u4Rdmwmx3ptNY',
    appId: '1:1024826384819:android:037d78c80f9d2573972bc6',
    messagingSenderId: '1024826384819',
    projectId: 'edukonsel',
    storageBucket: 'edukonsel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYHS-IxWWsbc2RSnG0ghlGgSGSc5AqtdA',
    appId: '1:1024826384819:ios:4f5c453a0305201b972bc6',
    messagingSenderId: '1024826384819',
    projectId: 'edukonsel',
    storageBucket: 'edukonsel.appspot.com',
    iosClientId: '1024826384819-uaq0abf886550m57g9n55sj6bhovslsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.edukonsel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYHS-IxWWsbc2RSnG0ghlGgSGSc5AqtdA',
    appId: '1:1024826384819:ios:4f5c453a0305201b972bc6',
    messagingSenderId: '1024826384819',
    projectId: 'edukonsel',
    storageBucket: 'edukonsel.appspot.com',
    iosClientId: '1024826384819-uaq0abf886550m57g9n55sj6bhovslsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.edukonsel',
  );
}
